### ISSUE TITLE
npm install 无法安装

### ISSUE THREAD

**Issue by velomarc** [reactive-react/xreact#38]
![image](https://user-images.githubusercontent.com/22446702/28297858-c003377c-6ba2-11e7-9ef4-86cade4d3c76.png)

**Comment by jcouyang** [comment]
这就是已经装上了呀，warning只是提醒你rxjs或者most是peer dependancy，不是xreact的直接依赖
也就是说你用xreact的项目要有rxjs或most才行。具体可以参考xreact/examples底下的例子

**Comment by jcouyang** [comment]
peer dependancy: https://nodejs.org/en/blog/npm/peer-dependencies/

**Comment by velomarc** [comment]
囧rz, 膜拜大神。
不好意思，提了弱智问题

**Comment by jcouyang** [comment]
大丈夫
