### ISSUE TITLE
react警告

### ISSUE THREAD

**Issue by songdun** [reactive-react/xreact#4]
warning.js:36 Warning: You are manually calling a React.PropTypes validation function for the `__reactive.react.flatObserve__` prop on `<<anonymous>>`. This is deprecated and will not work in production with the next major version. You may be seeing this warning due to a third-party PropTypes library. See https://fb.me/react-warning-dont-call-proptypes for details.

**Comment by jcouyang** [comment]
你的react什么版本？
如果不是15，应该升级一下就好了
