### ISSUE TITLE
兄弟组件通信

### ISSUE THREAD

**Issue by songdun** [reactive-react/xreact#5]
请问有没有关于兄弟组件通信的最佳实践demo？

**Comment by jcouyang** [comment]
不知道 https://github.com/reactive-react/react-most/tree/master/examples/todomvc 中有没有你要找到答案，如果还有问题，可以到聊天室问问 -> [![Join the chat at https://gitter.im/jcouyang/react-most](https://badges.gitter.im/jcouyang/react-most.svg)](https://gitter.im/jcouyang/react-most?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge)
