### ISSUE TITLE
当出现flatMapError时，就不能再运行了吗？

### ISSUE THREAD

**Issue by songdun** [reactive-react/xreact#6]
当出现flatMapError时，就不能再运行了吗？
产生情况如下：
search-type这个例子
正常情况下是可以一直重复发送请求并显示查询结果，但当认为断网使其报错再连上网时，它只会发送请求，而请求结果不能显示在下方，我用chrome的react插件看该组件的state也没有改变

**Comment by jcouyang** [comment]
`flatMapError`  跟命令式程序最外面的catch一样，它使整个stream能恢复到一个backup stream，但已经不能恢复到原来
对于可能会挂的比如 `rest`, 需要用promise的catch来recover，恢复正常
函数内命令式的try catch也一样
